import { Epilogue} from "next/font/google";
import "./globals.css";


const epilogue = Epilogue({
    variable: "--font-epilogue",
    subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.variable} ${epilogue.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
